### ISSUE TITLE
`db:create` fails in postgres

### ISSUE THREAD

**Issue by jgeggatt** [Originate/grape_press#1]
I set up a new grape_press app using postgres, and when I tried to run `rake db:create`, I got the following error:

```
ActiveRecord::NoDatabaseError: FATAL:  database "jgeggatt" does not exist
```

According to [a sample Grape/Goliath app](https://github.com/djones/grape-goliath-example/blob/master/Rakefile#L12), `drop` and `create` need to be performed with a connection the 'postgres' (system) database.  The following change to the `establish_connection` call fixed it for me:

```
ActiveRecord::Base.establish_connection config.merge(database: 'postgres')
```

**Comment by alexpeachey** [comment]
Thank you, addressed in v0.0.2.
